version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: hoang2003
      MYSQL_DATABASE: nestjs-test
      MYSQL_USER: root
      MYSQL_PASSWORD:

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD:
      DB_DATABASE: nestjs-test
    depends_on:
      - db
